export const HF = {
    accept: 'Accept',
    'accept-contact': 'Accept-Contact',
    a: 'Accept-Contact',
    'accept-encoding': 'Accept-Encoding',
    'accept-language': 'Accept-Language',
    'alert-info': 'Alert-Info',
    allow: 'Allow',
    'allow-event': 'Allow-Event',
    u: 'Allow-Event',
    'authentication-info': 'Authentication-Info',
    authorization: 'Authorization',
    'call-id': 'Call-ID',
    i: 'Call-ID',
    'call-info': 'Call-Info',
    contact: 'Contact',
    m: 'Contact',
    'content-disposition': 'Content-Disposition',
    'content-encoding': 'Content-Encoding',
    e: 'Content-Encoding',
    'content-language': 'Content-Language',
    'content-length': 'Content-Length',
    l: 'Content-Length',
    'content-type': 'Content-Type',
    c: 'Content-Type',
    cseq: 'CSeq',
    date: 'Date',
    'error-info': 'Error-Info',
    expires: 'Expires',
    event: 'Event',
    o: 'Event',
    from: 'From',
    f: 'From',
    'in-reply-to': 'In-Reply-To',
    'max-forwards': 'Max-Forwards',
    'min-expires': 'Min-Expires',
    'mime-version': 'MIME-Version',
    organization: 'Organization',
    priority: 'Priority',
    'proxy-authenticate': 'Proxy-Authenticate',
    'proxy-authorization': 'Proxy-Authorization',
    'proxy-require': 'Proxy-Require',
    'record-route': 'Record-Route',
    'reply-to': 'Reply-To',
    require: 'Require',
    'retry-after': 'Retry-After',
    route: 'Route',
    server: 'Server',
    subject: 'Subject',
    s: 'Subject',
    supported: 'Supported',
    timestamp: 'Timestamp',
    to: 'To',
    t: 'To',
    unsupported: 'Unsupported',
    'user-agent': 'User-Agent',
    via: 'Via',
    v: 'Via',
    warning: 'Warning',
    'www-authenticate': 'WWW-Authenticate',
    'refer-to': 'Refer-To',
    r: 'Refer-To',
    'Referred-By': 'Referred-By',
    b: 'Referred-By',
    'Reject-Contact': 'Reject-Contact',
    j: 'Reject-Contact',
}

export const statusDesc = {
    100: 'Trying',
    180: 'Ringing',
    181: 'Call Is Being Forwarded',
    182: 'Queued',
    183: 'Session Progress',
    200: 'OK',
    300: 'Multiple Choices',
    301: 'Moved Permanently',
    302: 'Moved Temporarily',
    305: 'Use Proxy',
    380: 'Alternative Service',
    400: 'Bad Request',
    401: 'Unauthorized',
    402: 'Payment Required',
    403: 'Forbidden',
    404: 'Not Found',
    405: 'Method Not Allowed',
    406: 'Not Acceptable',
    407: 'Proxy Authentication Required',
    408: 'Request Timeout',
    410: 'Gone',
    413: 'Request Entity Too Large',
    414: 'Request-URI Too Long',
    415: 'Unsupported Media Type',
    416: 'Unsupported URI Scheme',
    420: 'Bad Extension',
    421: 'Extension Required',
    423: 'Interval Too Brief',
    480: 'Temporarily Unavailable',
    481: 'Call/Transaction Does Not Exist',
    482: 'Loop Detected',
    483: 'Too Many Hops',
    484: 'Address Incomplete',
    485: 'Ambiguous',
    486: 'Busy Here',
    487: 'Request Terminated',
    488: 'Not Acceptable Here',
    491: 'Request Pending',
    493: 'Undecipherable',
    500: 'Server Internal Error',
    501: 'Not Implemented',
    502: 'Bad Gateway',
    503: 'Service Unavailable',
    504: 'Server Time-out',
    505: 'Version Not Supported',
    513: 'Message Too Large',
    600: 'Busy Everywhere',
    603: 'Decline',
    604: 'Does Not Exist Anywhere',
    606: 'Not Acceptable',
}
